runs-on: ubuntu-24.04

steps:
  - name: Install Ruby using rbenv
    uses: actions/checkout@v3  # This fetches your code from the repository
  - name: Install rbenv and ruby-build
    run: |
      curl -sL https://raw.githubusercontent.com/rbenv/rbenv-installer/master/installer | bash
      echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
      source ~/.bashrc
      rbenv install ruby-build
  - name: Install Ruby 3.1.4
    run: |
      rbenv install 3.1.4
      rbenv global 3.1.4
      ruby-build --prefix /opt/hostedtoolcache/Ruby/3.1.4 x64
  - name: Mark Ruby installation complete
    run: touch /opt/hostedtoolcache/Ruby/3.1.4/x64.complete

    


name: Build Academic Page

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 # Match your academicpages Ruby version
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install

      - name: Build site
        run: |
          bundle exec jekyll build

      - name: Deploy site (if applicable)
        if: github.event_name == 'push'
        run: |
          echo "Deployment step (add your custom deploy commands if needed)"
